### ISSUE TITLE
Compilation issue following guide 'Compile on the Host'

### ISSUE THREAD

**Issue by troubas** [eeros-project/eeros-framework#57]
Hi all!

Not sure where the source of the issue is but maybe it's obvious to one of you. I figured I'd let you know. In case this isn't just a special case of my local environment (gcc-13, archlinux).

Following the guide [Compile on the Host](https://wiki.eeros.org/getting_started/compile_eeros_host) I'm getting an error for types of `cstdint`

```
eeros/includes/eeros/math/Matrix.hpp:984:15: error: ‘uint8_t’ has not been declared
  984 |   const T get(uint8_t m, uint8_t n) const { return (*this)(m, n); }

...

note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
    6 | #include <list>
```

So I added it - and hooray :tada: it works.

```diff
diff --git a/includes/eeros/math/Matrix.hpp b/includes/eeros/math/Matrix.hpp
index a4228d8..d94b956 100644
--- a/includes/eeros/math/Matrix.hpp
+++ b/includes/eeros/math/Matrix.hpp
@@ -7,6 +7,7 @@
 #include <utility>
 #include <sstream>
 #include <cstdlib>
+#include <cstdint>
 #include <cmath>
 #include <vector>
```

**Comment by ursgraf** [comment]
You are right, cstdint should definitely be included. In most cases it will be pulled in anyway sooner or later, depending on your local setup. Thank you for pointing it out. May I ask you to do a pull request?
